apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-js-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-js
  template:
    metadata:
      labels:
        app: react-js
    spec:
      containers:
        - name: react-js
          image: sanjueranga/my-react-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: $API_ELB_PUBLIC_FQDN
            - name: REACT_APP_CSUP_API_KEY
              value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: react-js-service
spec:
  type: LoadBalancer
  selector:
    app: react-js
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
