---
apiVersion: v1
kind: Namespace
metadata:
  name: sanju
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sanju
  name: api-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: api
        image: sanjueranga/my-node-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8060
        env:
          - name: MONGODB_URL
            value: "mongodb+srv://dbuser:DbUsEr@memberdb.f9jis.mongodb.net/approved_db?retryWrites=true&w=majority"
          - name:  CSUP_API_KEY
            value: 6LfBgjggAAAAAFQybxFfng2wyB2Uadi1HoGAciZa
          - name: JWT_SECRET
            value: abc123
---
apiVersion: v1
kind: Service
metadata:
  namespace: sanju
  name: service-api
spec:
  ports:
    - port: 8060
      targetPort: 8060
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: api
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
